### ISSUE TITLE
Zone Damage

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#1]
**Description**
The player takes damage when entering any zone that has a floor type that imparts damage, regardless of whether or not the player is in contact with the floor. Since the game supports both jumping and flying (after collecting the jetpack) this behaviour is a bit nonsensical.

**Affects**
- Original game
- Current iteration

**Suggested Behaviour**
Check that the player is in contact with the floor when processing floor damage. If there is not a simple flag that can be tested, the player's height relative to the floor could also be used

**Comment by mheyer32** [comment]
https://github.com/mheyer32/alienbre...hires.s#L10069

This is where I believe floor damage is indiscriminately applied. There needs to be a check for flying or jumping...

**Comment by 0xABADCAFE** [comment]
It's duplicated a couple of lines further down (line 10083) for player 2 (death match)

**Comment by 0xABADCAFE** [comment]
When replaying a level just now, I found that the short range attack of the red dog alien exhibits something similar, able to bite me as long as I am in the same zone at a close enough 2D coordinate despite a significant vertical separation (falling down a shaft).

**Comment by 0xABADCAFE** [comment]
Implemented as suggested, based on current height tests. Includes test against the zone water height so that the floor damage can be extended to the full depth of liquid above the floot
