### ISSUE TITLE
Suggestion: Assign Simplification

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#15]
While the Game Link file can specify files, there are still some dependencies on `tkg1:` and `tkg2:` in literal string definitions in the sourcecode. It might be nice to just make all of these `ab3:` which tends to be assigned to the game installation directory by default. Perhaps even `PROGDIR:` if that will work.

**Comment by mheyer32** [comment]
We can do that pretty easily. It removes the ability to run the game from floppy, but I guess.. who cares?

**Comment by 0xABADCAFE** [comment]
Resolved.
