### ISSUE TITLE
Feature Request: Configuration File

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#3]
It would be useful if the input control bindings and other options (render mode, audio mode etc) could be stored in a simple user editable text file that's loaded on startup.

As the game does not presently have a clean exit routine, there's no immediate need to make this auto save.

**Comment by mheyer32** [comment]
There are some provisions to store the "preferences" in a file. The code has "Prefsname", "Prefshandle" symbols to open a file, but doesn't use them. "Prefsfile" stores 4 bytes of settings; but key assignments are not part of it yet.

**Comment by 0xABADCAFE** [comment]
I think it's time to pick this one up.
