### ISSUE TITLE
Crash on level restart

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#35]
Current builds of the engine have a tendency to fail when replaying a level. The result is usually a hard hang. May or may not be affected by JIT status in UAE (TBC).

Steps to reproduce:
- Start game.
- (Optionally) load a saved position
- Begin level
- Exit level without completing
- Restart level

**Comment by 0xABADCAFE** [comment]
Additional:
- For UAE, does appear to be impacted by whether or not JIT is enabled.
- For UAE (with the changes included in https://github.com/mheyer32/alienbreed3d2/pull/29) the issue does not seem to occur when the frame limit is set to 25 or lower.

**Comment by ZyberSE** [comment]
This happens in Pimiga 3 (Amiberry 5.5b) too.

**Comment by mheyer32** [comment]
I just tested in WinUAE in a clean OS 3.1 environment... the problem seems to have gotten worse. When loading a savegame, the game returns to the main menu but the cursor won't appear again and no input will be possible.

**Comment by 0xABADCAFE** [comment]
This issue is no longer reproducible for me in recent builds. Level restart is just fine, whether from a saved game or not.
