### ISSUE TITLE
Defect: UAE/Memory Requirements

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#4]
**Description**
Current iterations of the build fail on startup in UAE if the 32-bit Chip Memory setting is not raised to at least 16MB
- Z3 Fast Ram setting has no effect
- Raising "vanilla" Chip RAM to the maximum of 8MB is not sufficient. However, this may work with the original game files.

**Affects**
UAE, WinUAE

It appears that the game is trying to use MEMF_CHIP for allocations that ought to be allocated as fast.

**Comment by mheyer32** [comment]
Dynamic memory gets allocated here
https://github.com/mheyer32/alienbreed3d2/blob/main/ab3d2_source/hires.s#L132  (fastmem)
https://github.com/mheyer32/alienbreed3d2/blob/main/ab3d2_source/screensetup.s#L1 (chipmem)

as well as the loading code in 
https://github.com/mheyer32/alienbreed3d2/blob/main/ab3d2_source/newloadfromdisk.s

The function QUEUEFILE looks at global variable TYPEOFMEM (which contains MEMF_CHIP flags and the like) and stores the loading request in a queue.

I went through the code to find if we're accidentally allocating chipmem in places, but didn't pan out. THe allocations seem alright.
Also, I do run in WinUAE most of the time, so I'm baffled that so many people have issues with it. 

One difference might be that I'm running the game from a start script:

```
stack 200000
assign tkg1: ""
assign tkg2: tkg1:
assign sfx: tkg1:
assign ab3: tkg1:
assign ab3d2: tkg1:

cd tkg1:
hires
```

**Comment by 0xABADCAFE** [comment]
To reproduce the failure, go to the Memory settings in (Win)UAE and make sure that you have:
- 2MB of Chip RAM (the "vanilla" variant Chip RAM).
- Minimum 16MB Z3 Fast memory.
-  Set "32-bit Chip" RAM to 0

The current build seems to be dependent on having the latter 32-bit Chip RAM set to 16MB (at least) and ignores whatever the regular Fast RAM is set to. This could be an issue with UAE if the game is working on real HW, of course.

**Comment by 0xABADCAFE** [comment]
An additional fact that may be relevant. An older build assembled using devpac did not exhibit this behaviour under UAE.

**Comment by 0xABADCAFE** [comment]
I've rebuilt without -sc and -sd options for the linker but I still end up with UAE only working with the 32-bit addressable CHIP ram available.

**Comment by 0xABADCAFE** [comment]
I no longer believe this is an allocation requirement issue, I'm reaonably sure the memory allocations are being made in FAST or real chip. The fact that the game can run with no fast ram on UAE as long as there is 32-bit chip ram is due to the fact that the non chip allocation requests depend on MEMF_ANY which of course falls back.

I'm more inclined to believe that this is an illegal memory access to the memory window where UAE places the new class of 32-bit chip memory. Other than what you've already found though I can't say exactly where it's happening. I'm inclined to think it's some form of action at a distance, i.e. the screen/viewport/window/other system structure is missing or has a value set that triggers the access from within the library code somewhere.

**Comment by 0xABADCAFE** [comment]
I'm closing this issue as it does not properly describe the issue, only what it superficially seemed to be.
