### ISSUE TITLE
"Shaking" with JIT enabled

### ISSUE THREAD

**Issue by ZyberSE** [mheyer32/alienbreed3d2#42]
I just tested the latest .exe found on abime.net in Pimiga 3. It run and sometimes hits 50fps but the whole view "shakes" when moving the mouse.

If I disable JIT it runs fine, though at a much lower fps.

**Comment by mheyer32** [comment]
This is probably an old build. 
Abu is regularly posting new build at EAB: Compileable version of Alien Breed 3D II - The Killing Grounds
 https://r.tapatalk.com/shareLink/topic?share_fid=63860&share_tid=111090&url=http%3A%2F%2Feab%2Eabime%2Enet%2Fshowthread%2Ephp%3Ft%3D111090&share_type=t&link_source=app

(In the "Zone")

**Comment by ZyberSE** [comment]
It was the latest exec I could find posted in that thread. I downloaded ABD3D2_Blizz1260.lha, replaced test.ink with the one linked in a message and took hires_new.LHA from this message: http://eab.abime.net/showpost.php?p=1581014&postcount=1061

A side note. Would it be possible for you to check in a fresh exec from time to time? When it make sense?

**Comment by AndyLoft** [comment]
I have re-downloaded an tested this buils and this must be an emulator issue surely as it works in both winuae and on real amiga hardware without any issues.

**Comment by ZyberSE** [comment]
Interesting, this is a great game and your (teams) improvements have really made it much more playable and I can only dream of what well it'll work after the porting and optimizations.
I'm on the Pimiga team and would really like to figure out what could be the issue and see if we can find a solution or help you somehow to do so.

**Comment by AndyLoft** [comment]
I will pull the current main and post a built to eab for you to test.

**Comment by AndyLoft** [comment]
done.
https://eab.abime.net/showpost.php?p=1582511&postcount=1170

**Comment by ZyberSE** [comment]
Thank you @AndyLoft, I've just tried it but unfortunately there were no improvements. If you have Discord please add me and I'll send you a video of it there. ZyBeR#8378

**Comment by AndyLoft** [comment]
@ZyberSE
after our chat on discord, for now I think this is bumped to a low priority as it may be an emulator issue and with the direction the code is going, may just disappear.

**Comment by mheyer32** [comment]
I've seen the videos now. Almost looks like tearing due to missing VSYNC waits

**Comment by ZyberSE** [comment]
It seams like this is issue is related to PAL/NTSC, check this video out.
https://imgur.com/a/sIA2W2Q

With PAL enabled (default in Pimiga) it's like in the previous videos, but selecting NTSC it's much better.

**Comment by AndyLoft** [comment]
most odd, but if it works for you that's fab

**Comment by 0xABADCAFE** [comment]
Closing this issue.
