### ISSUE TITLE
Defect: Crash on submersion

### ISSUE THREAD

**Issue by 0xABADCAFE** [mheyer32/alienbreed3d2#5]
**Description**
Level F of KarlosTKG contains a submerged zone that the player is supposed to traverse to reach a teleporter. On entering the zone, once the player's view is below the surface, the game hangs.
- Does not occur with the original binary.
- There are rendering artefacts that look like they could be related to the recently added 320 pixel width.
- Does not manifest at 2/3 screen size
- Does not always manifest as a crash. When the game does not crash, there are other issues, e.g corrupted sprites and sound effects, again suggesting a buffer overrun caused by the 320 width.

Before enterng
![bug-water-f-before](https://user-images.githubusercontent.com/27722116/184689132-d85bf8ac-f5cc-4d8f-82c7-6853cfeb83e5.png)

After entering
![level-f-water-bug-after](https://user-images.githubusercontent.com/27722116/184689141-562097ed-87e5-47a1-b419-26efcb8b7692.png)

**Comment by 0xABADCAFE** [comment]
I think this could be the same problem as noted in the README for the original Level C, which has a submerged zone the player can enter.

**Comment by mheyer32** [comment]
Can you please provide a savegame (boot.dat) that has level F available?

**Comment by 0xABADCAFE** [comment]
If you have the same copy of the mod that was shared on EAB, load up "Chasm of Pain" which is what the level has been renamed to. Be prepared to run straight ahead to the lift, then turn left at the end of the chasm, then left again to get onto the other side of the chasm. I believe the level layout is more or less as it was (save the brutality) but the area where the teleporter was is now submerged, because ... frankly I don't recall. Probably because I thought it would be cool to confuse the player after running a gauntlet that kills you 90% of the time. Don't worry, the save game has ludicrious health and ammo.

**Comment by mheyer32** [comment]
I can reproduce the hang.

**Comment by mheyer32** [comment]
Seems to be connected to this line:
https://github.com/mheyer32/alienbreed3d2/blob/main/ab3d2_source/hires.s#L4680

`add.l	#SCREENWIDTH*FS_HEIGHT/2*2`

basically points to the end of the buffer and subsequent writes go outside the screen, destroying whatever there is.

replacing it with:
'add.l	#SCREENWIDTH*FS_HEIGHT/2'

Lets the program live, but the water effect looks weird

**Comment by 0xABADCAFE** [comment]
I realise this is closed, but is the problem not that the end of buffer calculation is wrong rather the actual buffer allocation size is wrong?
